server:
  port: 8080


eureka: 
 instance:
  hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud: 
   gateway: 
    routes: 
     - id: ADMIN-SERVICE
       uri: lb://ADMIN-SERVICE 
       predicates: 
        - Path=/api/admin/**
        
     - id: ADMIN-SERVICE
       uri: lb://ADMIN-SERVICE 
       predicates: 
        - Path=/api/public/**
        
     - id: QUESTION-SERVICE
       uri: lb://QUESTION-SERVICE 
       predicates: 
          - Path=/api/question/**
        
     - id: RESULT-SERVICE
       uri: lb://RESULT-SERVICE 
       predicates: 
          - Path=/api/result/**
        
     - id: STUDENT-SERVICE
       uri: lb://STUDENT-SERVICE 
       predicates: 
          - Path=/api/student/**